config {
  type: "table",
  schema: "seo_dashboard_03_viz",
  bigquery: {
    partitionBy: "date",
    clusterBy: ["country"]
  }
}

SELECT
  date,
  CASE
    WHEN site_url = 'https://mutti-parma.com/us/' THEN 'US'
    WHEN site_url = 'https://mutti-parma.com/de/'	THEN 'DE'
    WHEN site_url = 'https://mutti-parma.com/dk/'	THEN 'DK'
    WHEN site_url = 'https://mutti-parma.com/en/'	THEN 'UK'
    WHEN site_url = 'https://mutti-parma.com/fi/'	THEN 'FI'
    WHEN site_url = 'https://mutti-parma.com/it/'	THEN 'IT'
    WHEN site_url = 'https://mutti-parma.com/no/'	THEN 'NO'
    WHEN site_url = 'https://mutti-parma.com/se/' THEN 'SE'
    WHEN site_url = 'https://mutti-parma.com/au/' THEN 'AU'
  END AS country,
  SUM(clicks) AS clicks,
  SUM(impressions) AS impressions,
  AVG(position) AS position
FROM
  ${ref("raw_seo_gsc_total")}
GROUP BY
  date,
  country,
  site_url